server:
  port: 8081
  servlet:
    context-path: /qq

spring:
  freemarker:
    charset: UTF-8
    check-template-location: true
    template-loader-path: ["classpath:/templates/"]
    suffix: .ftl


## app info
app:
  clientId: game-abcxyz
  secret: gameabcxyc