server:
  port: 8080
  servlet:
    context-path: /game

spring:
  freemarker:
    charset: UTF-8
    check-template-location: true
    template-loader-path: ["classpath:/templates/"]
    suffix: .ftl


## app info
app:
  authUrl: http://localhost:8081/qq/oauth2/authorize
  redirectUri: http://localhost:8080/game/oauth2/callback
  clientId: game-abcxyz
  secret: gameabcxyc