server:
  port: 8080
  servlet:
    context-path: /game

spring:
  freemarker:
    charset: UTF-8
    check-template-location: true
    template-loader-path: ["classpath:/templates/"]
    suffix: .ftl